apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: tcp-echo
  labels:
    env: dev
    owner: men
  annotations:
    openshift.io/display-name: "My Project"
    openshift.io/description: "This is my new project."
